### ISSUE TITLE
WebRTC fails initialization without access to camera and microphone

### ISSUE THREAD

**Issue by jahnotto** [microsoft/MixedReality-WebRTC#126] opened 2019-11-14 13:50 UTC
When I start a HoloLens 2 app with MR-WebRTC, the user is asked for permission to the microphone and camera. My app doesn't use the camera or microphone. However, if the user clicks "no", WebRTC fails initialization.

Is it possible to disable microphone and camera access? Commenting out the call to GetVideoCaptureDevicesAsync(...) in PeerConnection.Start() doesn't seem to make any difference.

**Comment by jahnotto** [comment] 2019-11-14 14:43
I guess it's the same issue as this: #124 . I'll close this if it's a duplicate.

**Comment by djee-ms** [comment] 2019-11-14 15:13
I assume this is a Unity app. In that case this is a UWP app, and the issue is with the Unity integration always requesting Audio + Video access unconditionally, even if no audio or video track is added, and interrupt the initializing if access is not granted:
https://github.com/microsoft/MixedReality-WebRTC/blob/1064da2ec5a9b6764d7ee08e29b929c091bd904d/libs/Microsoft.MixedReality.WebRTC.Unity/Assets/Microsoft.MixedReality.WebRTC.Unity/Scripts/PeerConnection.cs#L401

This can be changed, but the complexities around that are that `MediaCapture.InitializeAsync()`:
- must be called from the main UI thread
- must be called before any native C++ code tries to access the camera or microphone (otherwise the app crashes, as the native code doesn't do any permission check)
- is required only if audio and/or video tracks are added, which can happen at any point in the lifetime of the peer connection

The solution is probably to request permission each time a local audio or video track is enabled, which would be the cleanest and safest way. I think this might work.

#124 is not about UWP authorization, it's about the system-wide Windows 10 authorization for Desktop apps, which is different. The audio there is accessed during initializing, even when no track is added, and there is no way around it.

**Comment by jahnotto** [comment] 2019-11-15 08:14
If I will not need webcam and microphone access on the HoloLens (at least for now), would it be safe as a temporary local workaround to remove the calls to PeerConnection.RequestAccessAndInitAsync(CancellationToken token)?

**Comment by djee-ms** [comment] 2019-11-17 18:40
@jahnotto : yes, if you are careful to remember about the fact it will lead to crashes if you ever try to access the camera/microphone again, then I think it's safe to skip the request. I didn't try it myself, but hopefully the A/V modules will not try to initialize themselves (which is the issue with #124, but the codepath for Desktop is different).

By the way it seems that this issue is the same as #34 no? I thought I had already seen that, but I couldn't find the other issue until someone commented on it today.

**Comment by fibann** [comment] 2020-08-13 11:33
Fixed by using ADM2 (#507)

**Closed by fibann** 2020-08-13 11:33 UTC
Labels: bug
