### ISSUE TITLE
Get list of multimedia on the device

### ISSUE THREAD

**Issue by LiliyaMuray** [microsoft/MixedReality-WebRTC#480] opened 2020-07-24 07:44 UTC
I am developing a web remote desktop management application. This is a bundle of applications: {ASP.Net Core + WebRTC + SignalR + JS} and {WPF(Net Core + Signals + JS + WebRTC)}. I made WebRTC via the CefSharp browser connections. This is not very convenient and I have long dreamed of switching to the C#library. I like your project. It is very necessary and useful. But I couldn't find the usual functionality for getting a list of multimedia on the device.
Here is a basic example for selecting devices: [https://webrtc.github.io/samples/src/content/devices/input-output/](https://webrtc.github.io/samples/src/content/devices/input-output/).
To get the list I use this JS code in CefSharp:
`      async function getListDevice() {
            return await new Promise(function (resolve) {
                navigator.mediaDevices.enumerateDevices()
                    .then(XX => resolve(gotDevices(XX)))
                    .catch(ER => resolve(handleError(ER)));
            });
        }
        function gotDevices(deviceInfos) {
            var str = "";
            for (var i = 0; i !== deviceInfos.length; ++i) {
                const deviceInfo = deviceInfos[i];
                if ((deviceInfo.kind === 'audioinput') || (deviceInfo.kind === 'audiooutput') || (deviceInfo.kind === 'videoinput'))
                { str = str + ";" + deviceInfo.kind + "|" + deviceInfo.label + "|" + deviceInfo.deviceId; }
            }
            return str;
        }`
But I couldn't find any similar functionality in your code, just selecting 'videoinput' via 'DeviceVideoTrackSource.GetCaptureDevicesAsync()'.
In my app, I used the following JS code to select the camera and sound source:
`              //example of a query string 
                //ustr = "440114bd3e1bf7d8e17f271d26d620eda42a2426758b88f8b23127ae754085a6|6927fc7db67e5af8623dea0f96824e305e427a8a70dc685bdbec9c7fe7017d8c";
                //ustr = "-|6927fc7db67e5af8623dea0f96824e305e427a8a70dc685bdbec9c7fe7017d8c";
                //ustr = "440114bd3e1bf7d8e17f271d26d620eda42a2426758b88f8b23127ae754085a6|-";
                var uav = ustr.split("|");
                var constraints = {};
                offerOptions = {};
                if (uav[0] != "-") {
                    constraints.audio = {};
                    constraints.audio.deviceId = uav[0];
                    offerOptions.offerToReceiveAudio = 1;
                }
                else {
                    offerOptions.offerToReceiveAudio = 0;
                }
                if (uav[1] != "-") {
                    constraints.video = {};
                    constraints.video.deviceId = uav[1];
                    offerOptions.offerToReceiveVideo = 1;
                }
                else {
                    offerOptions.offerToReceiveVideo = 0;
                }
                window.navigator.mediaDevices.getUserMedia(constraints).then(gotStream).catch(e => console.log(`getUserMedia() error: ${e.message}`));`
I see a lot of questions about requesting audio source selection functions and specifying it when creating a connection. 
1. is it Possible to get a list of all devices using mediaDevices.enumerateDevices()?
2. is it Possible to specify a specific audio device when connecting?
Best regards,
Liliya Muray

**Comment by djee-ms** [comment] 2020-07-24 09:45
Hi @LiliyaMuray,

You can get a list of devices with [`DeviceVideoTrackSource.GetCaptureDevicesAsync()` ](https://microsoft.github.io/MixedReality-WebRTC/api/Microsoft.MixedReality.WebRTC.DeviceVideoTrackSource.html#Microsoft_MixedReality_WebRTC_DeviceVideoTrackSource_GetCaptureDevicesAsync) and a list of supported capture formats for a device with [`DeviceVideoTrackSource.GetCaptureFormatsAsync()`](https://microsoft.github.io/MixedReality-WebRTC/api/Microsoft.MixedReality.WebRTC.DeviceVideoTrackSource.html#Microsoft_MixedReality_WebRTC_DeviceVideoTrackSource_GetCaptureFormatsAsync_System_String_).

There is no device selection for audio. The default device is used.

**Comment by LiliyaMuray** [comment] 2020-07-24 10:04
Hi @djee-ms,
Yes, I read the forum posts. I'm interested to know what the problem is with implementing the usual WebRTC method "navigator.mediaDevices.enumerateDevices()" available in the browser? I think it would be better to make a single method with a list of devices, than to make methods separately for video And possibly other devices, as it is done now. And each user will select the type of device they need via "deviceInfo.kind".

**Comment by djee-ms** [comment] 2020-07-24 10:16
If I understand correctly what you suggest, I see no reason to have a method that enumerate all audio AND video devices, when all other API methods are using those devices separately, and the entire internal implementation is also separated between audio and video. Please also consider not all users use both audio and video; some only use one of those. The `mediaDevices` API is a web API independent of WebRTC, which enumerate all media devices for input AND output, something that is useless for us given outputs are already known.

**Comment by LiliyaMuray** [comment] 2020-07-24 10:29
@djee-ms 
In other words, your project will not be able to generate a multimedia stream of 3 tracks: video to choose from, microphone to choose from, speakers to choose from?
And You will not strive for this?

P.S. I apologize for my English, this is an online translation.

**Comment by djee-ms** [comment] 2020-07-24 10:47
> In other words, your project will not be able to generate a multimedia stream of 3 tracks: video to choose from, microphone to choose from, speakers to choose from?

This is wrong. This is not what I said, please do not make me say something I didn't. I said I see no argument for having a single method to enumerate all kinds of devices at the same time. This project does support multi-track. We currently do not support input audio device selection, although some users have asked for it and therefore this is something we are currently considering (but are busy right now with our upcoming 2.0.0 release, so had no time to implement yet; there are also challenges with the underlying Google audio implementation that makes things more difficult to implement for audio than for video). As for audio output, this is an entirely different issue since input and output are not configured at all at the same place, and do not even happen on the same peer/device, so I see no reason to mix them in the API, and I don't hear any argument in favor of it. And output is not a track.

> And You will not strive for this?

For your information, passive aggressive comments like this will not get you anywhere. We implement what we think is useful, and you are not bringing any argument other than "I think this is better". I proposed counter-arguments, explaining why things are the way they are, but you ignored them. I am always happy to consider user feedbacks for improvements when they are grounded in facts and have sound arguments to improve this project, with use cases that we have not yet considered and for which we can justify resourcing some of our time vs. other tasks and features.

**Comment by LiliyaMuray** [comment] 2020-07-24 11:21
@djee-ms 
I'm sorry if I seemed aggressive. I really want to use your library in my project. I have already accumulated some functionality for working with WebRTC, which includes a selection of multimedia devices, both video and audio. I am very sorry that your project does not have the basic functions that I need to work with multimedia. Why do I need this? Example: a laptop with a microphone, two cameras, and speakers is connected to a headset with a microphone. I want to get video from the camera (#2), from the headset I need the microphone sound, and from the speakers I need the Windows system sounds.

**Comment by djee-ms** [comment] 2020-07-24 13:48
As I explained, selection of video capture device is available, selection of audio capture device is not yet available but under consideration when we have time (see #167). Selection of output audio device is not available by direct selection but can be worked around by using some audio callbacks and outputting the audio yourself where you want; see the [`AudioRenderer.cs`](https://github.com/microsoft/MixedReality-WebRTC/blob/master/libs/unity/library/Runtime/Scripts/Media/AudioRenderer.cs) Unity code doing that for injecting the audio into the Unity DSP pipeline. If you need some other way, you can open a new feature request about it and detail your use case and why we should consider adding that feature.

The original request on the current issue is about an API to enumerate all audio/video input/output devices. I do not see any argument in favor of it. If you need this in your design then you can implement it yourself by enumerating separately the thing you need and merging all of them into a single list. If there is something I am missing or if you have arguments why we should do otherwise, please let us know. Otherwise we should close this issue.

**Comment by LiliyaMuray** [comment] 2020-07-24 14:07
@djee-ms 
Getting a list of audio inputs and getting an audio track by id is quite enough for now. It won't be difficult for me to call two functions. I understand that this is not a priority task, but can you give me an approximate time frame?

**Comment by djee-ms** [comment] 2020-07-28 09:20
No I can't. We are in the middle of a release and have not looked at next roadmap. And the initial investigation on #167 showed that due to Google's audio module design it is very difficult to implement audio device selection per track, because Google assumed a single central audio capture device for all tracks by design (see [Google bug](https://bugs.chromium.org/p/webrtc/issues/detail?id=11759) and [forum post](https://groups.google.com/g/discuss-webrtc/c/3H4vwWgNuQk/m/Nv-VnUsrBAAJ)).

I am closing this issue as duplicate of #167 since this seems to be the feature you are missing.

**Closed by djee-ms** 2020-07-28 09:20 UTC
