### ISSUE TITLE
How to confirm if LocalVideoTrack sent from HoloLens 2 to remote Peer?

### ISSUE THREAD

**Issue by rahulk131** [microsoft/MixedReality-WebRTC#353] opened 2020-05-16 10:04 UTC
Hello,

I'm using the Release 1.0 C# library. I'm using a modified TestAppUWP on the HoloLens 2 to make video call with another app running on a desktop. 

The problem I'm facing is that when I run the TestAppUWP on Hololens 2, the video is not rendered on the remote peer. However, when I run the TestAppUWP on a Win 10 Laptop, the video is rendered successfully on the remote peer.

One possibility appears to be that the HoloLens 2 is not encoding into H.264 and/or sending out the packets to the remote peer. On the Hololens 2, the Local video playback works fine, and the callback when an I420A Frame is received from local device (_localVideoTrack.I420AVideoFrameReady) also succeeds. Does this mean that the video frame is also being successfully encoded into H.264 (preferred video codec) and sent out to the remote peer? Is there anyway for me to confirm this? 

The other possibility I'm not seeing video on the remote peer is that maybe the remote peer is receiving the frames, but is not rendering it because of, say a mis-match in the video profile and resolution. But the rendering on remote peer works fine when the local peer is a Win 10 laptop. When I use the exact same profile Id and resolution on the Hololens, the rendering doesn't work on the remote peer. The Remote peer is constant in both these cases - Win 10 laptop.

I've also ensured no other apps are using H.264 encoding on the Hololens device while I was running this.

For reference, here's how the Local tracks are added to the peer connection:
await _peerConnection.AddLocalAudioTrackAsync();
var trackConfig = new LocalVideoTrackSettings
{
    trackName = "local_video",
    videoDevice = captureDeviceInfo,
    videoProfileId = videoProfileId,
    videoProfileKind = SelectedVideoProfileKind,
    width = width,
    height = height,
    framerate = framerate,
    enableMrc = false
};
_localVideoTrack = await _peerConnection.AddLocalVideoTrackAsync(trackConfig);

Thanks,
Rahul

**Comment by djee-ms** [comment] 2020-05-17 10:12
Hi,

> Does this mean that the video frame is also being successfully encoded into H.264 (preferred video codec) and sent out to the remote peer? Is there anyway for me to confirm this?

No, and no. Though I doubt this is the issue, unless the video track is not negotiated correctly, but I can't tell without the SDP messages.

> is not rendering it because of, say a mis-match in the video profile and resolution.

There is no concept of video profile or resolution on the receiving peer. This is only used to configure the local webcam, and only on UWP. WebRTC doesn't even know what a video profile is. And the resolution is sent per frame alongside the video frame itself, not pre-configured, so by design there is nothing for it to be mismatching with.

Could you please:
- Try not to add the audio track, to see if there's a negotiation timing issue.
- Try not to constraint the width/height/framerate and let the implementation peek one instead, to see if you are over-constraining. In particular framerate constraints are flaky; it only works if you are setting a value previously retrieved by enumerating the supported capture formats. You cannot just set `30.0` and expect it to work, because the device might list `29.9999999` and that will mismatch.
- Paste the SDP offer/answer in both cases, to see if there's a difference and whether the video track is correctly negotiated.

**Comment by rahulk131** [comment] 2020-05-18 19:52
When Both Local Audio and Local Video Tracks are added to the PeerConnection:

The SDP Offer:

v=0
o=- 1541093106195153007 2 IN IP4 127.0.0.1
s=-
t=0 0
a=group:BUNDLE 0 1
a=msid-semantic: WMS local_av_stream
m=audio 9 UDP/TLS/RTP/SAVPF 111 103 9 102 0 8 105 13 110 113 126
b=TIAS:64000
c=IN IP4 0.0.0.0
a=rtcp:9 IN IP4 0.0.0.0
a=ice-ufrag:+sKI
a=ice-pwd:oAaSqibMeGXmi3Kjt2TQtN/7
a=ice-options:trickle
a=fingerprint:sha-256 D1:F5:3C:92:AA:A0:70:AE:CA:82:B1:9F:20:4B:4D:82:B4:5B:59:D3:70:26:18:4F:3C:62:32:38:11:0C:C2:41
a=setup:actpass
a=mid:0
a=extmap:1 urn:ietf:params:rtp-hdrext:ssrc-audio-level
a=extmap:9 urn:ietf:params:rtp-hdrext:sdes:mid
a=sendrecv
a=msid:local_av_stream local_audio
a=rtcp-mux
a=rtpmap:111 opus/48000/2
a=rtcp-fb:111 transport-cc
a=fmtp:111 minptime=10;useinbandfec=1
a=rtpmap:103 ISAC/16000
a=rtpmap:9 G722/8000
a=rtpmap:102 ILBC/8000
a=rtpmap:0 PCMU/8000
a=rtpmap:8 PCMA/8000
a=rtpmap:105 CN/16000
a=rtpmap:13 CN/8000
a=rtpmap:110 telephone-event/48000
a=rtpmap:113 telephone-event/16000
a=rtpmap:126 telephone-event/8000
a=ssrc:1454952447 cname:AjgOFH9AoL1fRy2Z
a=ssrc:1454952447 msid:local_av_stream local_audio
a=ssrc:1454952447 mslabel:local_av_stream
a=ssrc:1454952447 label:local_audio
m=video 9 UDP/TLS/RTP/SAVPF 100
b=TIAS:4000000
c=IN IP4 0.0.0.0
a=rtcp:9 IN IP4 0.0.0.0
a=ice-ufrag:+sKI
a=ice-pwd:oAaSqibMeGXmi3Kjt2TQtN/7
a=ice-options:trickle
a=fingerprint:sha-256 D1:F5:3C:92:AA:A0:70:AE:CA:82:B1:9F:20:4B:4D:82:B4:5B:59:D3:70:26:18:4F:3C:62:32:38:11:0C:C2:41
a=setup:actpass
a=mid:1
a=extmap:2 urn:ietf:params:rtp-hdrext:toffset
a=extmap:3 http://www.webrtc.org/experiments/rtp-hdrext/abs-send-time
a=extmap:4 urn:3gpp:video-orientation
a=extmap:5 http://www.ietf.org/id/draft-holmer-rmcat-transport-wide-cc-extensions-01
a=extmap:6 http://www.webrtc.org/experiments/rtp-hdrext/playout-delay
a=extmap:7 http://www.webrtc.org/experiments/rtp-hdrext/video-content-type
a=extmap:8 http://www.webrtc.org/experiments/rtp-hdrext/video-timing
a=extmap:10 http://tools.ietf.org/html/draft-ietf-avtext-framemarking-07
a=extmap:9 urn:ietf:params:rtp-hdrext:sdes:mid
a=sendrecv
a=msid:local_av_stream local_video
a=rtcp-mux
a=rtcp-rsize
a=rtpmap:100 H264/90000
a=rtcp-fb:100 goog-remb
a=rtcp-fb:100 transport-cc
a=rtcp-fb:100 ccm fir
a=rtcp-fb:100 nack
a=rtcp-fb:100 nack pli
a=fmtp:100 profile-level-id=42e01f;packetization-mode=1;max-fs=8160
a=ssrc-group:FID 3993736492 3580006070
a=ssrc:3993736492 cname:AjgOFH9AoL1fRy2Z
a=ssrc:3993736492 msid:local_av_stream local_video
a=ssrc:3993736492 mslabel:local_av_stream
a=ssrc:3993736492 label:local_video
a=ssrc:3580006070 cname:AjgOFH9AoL1fRy2Z
a=ssrc:3580006070 msid:local_av_stream local_video
a=ssrc:3580006070 mslabel:local_av_stream
a=ssrc:3580006070 label:local_video`


The SDP Answer:

v=0
o=linus 0 1 IN IP4 170.133.146.100
s=-
c=IN IP4 170.133.146.100
b=TIAS:664000
t=0 0
a=ice-lite
m=audio 5004 UDP/TLS/RTP/SAVPF 98 101
c=IN IP4 170.133.146.100
b=TIAS:64000
a=content:main
a=sendrecv
a=rtpmap:98 opus/48000/2
a=fmtp:98 maxplaybackrate=48000;maxaveragebitrate=64000;stereo=1
a=rtpmap:101 telephone-event/8000
a=fmtp:101 0-15
a=rtcp-mux
a=label:100
a=mid:0
a=ice-ufrag:dwda0XX2
a=ice-pwd:4jBTSoBS/9H4APOXXhnhq7qu6yIDEXuG
a=setup:passive
a=fingerprint:sha-1 F7:E7:80:0A:F5:CF:63:BD:14:E4:29:82:DC:D2:AD:60:77:91:2B:08
m=video 5004 UDP/TLS/RTP/SAVPF 108
c=IN IP4 170.133.146.100
b=TIAS:600000
a=content:main
a=sendrecv
a=rtpmap:108 H264/90000
a=fmtp:108 profile-level-id=42400C;packetization-mode=1;max-mbps=27600;max-fs=920;max-fps=3000;max-br=600;max-dpb=891;level-asymmetry-allowed=1
a=rtcp-fb:* nack pli
a=rtcp-fb:* ccm fir
a=extmap:3/sendrecv urn:ietf:params:rtp-hdrext:toffset
a=extmap:5/sendrecv urn:3gpp:video-orientation
a=rtcp-mux
a=label:200
a=mid:1
a=ice-ufrag:esdthOCl
a=ice-pwd:Ojlx5bGNl112T0/v0k1UAD/nK0t/q6jR
a=setup:passive
a=fingerprint:sha-1 F7:E7:80:0A:F5:CF:63:BD:14:E4:29:82:DC:D2:AD:60:77:91:2B:08

**Comment by rahulk131** [comment] 2020-05-18 19:53
When Local Audio Track Not added to Peer Connection


SDP offer: 

v=0
o=- 640464239903095692 2 IN IP4 127.0.0.1
s=-
t=0 0
a=group:BUNDLE 0 1
a=msid-semantic: WMS local_av_stream
m=video 9 UDP/TLS/RTP/SAVPF 100
b=TIAS:4000000
c=IN IP4 0.0.0.0
a=rtcp:9 IN IP4 0.0.0.0
a=ice-ufrag:W9mA
a=ice-pwd:Af/6k8LLam6SAsC0dFboz8m/
a=ice-options:trickle
a=fingerprint:sha-256 FF:57:85:83:35:6D:ED:19:58:77:4E:15:EB:F5:0C:51:F2:23:53:00:2E:AF:6D:80:C3:B7:CF:A9:3F:5C:F3:16
a=setup:actpass
a=mid:0
a=extmap:2 urn:ietf:params:rtp-hdrext:toffset
a=extmap:3 http://www.webrtc.org/experiments/rtp-hdrext/abs-send-time
a=extmap:4 urn:3gpp:video-orientation
a=extmap:5 http://www.ietf.org/id/draft-holmer-rmcat-transport-wide-cc-extensions-01
a=extmap:6 http://www.webrtc.org/experiments/rtp-hdrext/playout-delay
a=extmap:7 http://www.webrtc.org/experiments/rtp-hdrext/video-content-type
a=extmap:8 http://www.webrtc.org/experiments/rtp-hdrext/video-timing
a=extmap:10 http://tools.ietf.org/html/draft-ietf-avtext-framemarking-07
a=extmap:9 urn:ietf:params:rtp-hdrext:sdes:mid
a=sendrecv
a=msid:local_av_stream local_video
a=rtcp-mux
a=rtcp-rsize
a=rtpmap:100 H264/90000
a=rtcp-fb:100 goog-remb
a=rtcp-fb:100 transport-cc
a=rtcp-fb:100 ccm fir
a=rtcp-fb:100 nack
a=rtcp-fb:100 nack pli
a=fmtp:100 profile-level-id=42e01f;packetization-mode=1;max-fs=8160
a=ssrc-group:FID 3082858118 3873205121
a=ssrc:3082858118 cname:Ib3d3ZfGNHJMFajI
a=ssrc:3082858118 msid:local_av_stream local_video
a=ssrc:3082858118 mslabel:local_av_stream
a=ssrc:3082858118 label:local_video
a=ssrc:3873205121 cname:Ib3d3ZfGNHJMFajI
a=ssrc:3873205121 msid:local_av_stream local_video
a=ssrc:3873205121 mslabel:local_av_stream
a=ssrc:3873205121 label:local_video
m=audio 9 UDP/TLS/RTP/SAVPF 111 103 9 102 0 8 105 13 110 113 126
b=TIAS:64000
c=IN IP4 0.0.0.0
a=rtcp:9 IN IP4 0.0.0.0
a=ice-ufrag:W9mA
a=ice-pwd:Af/6k8LLam6SAsC0dFboz8m/
a=ice-options:trickle
a=fingerprint:sha-256 FF:57:85:83:35:6D:ED:19:58:77:4E:15:EB:F5:0C:51:F2:23:53:00:2E:AF:6D:80:C3:B7:CF:A9:3F:5C:F3:16
a=setup:actpass
a=mid:1
a=extmap:1 urn:ietf:params:rtp-hdrext:ssrc-audio-level
a=extmap:9 urn:ietf:params:rtp-hdrext:sdes:mid
a=recvonly
a=rtcp-mux
a=rtpmap:111 opus/48000/2
a=rtcp-fb:111 transport-cc
a=fmtp:111 minptime=10;useinbandfec=1
a=rtpmap:103 ISAC/16000
a=rtpmap:9 G722/8000
a=rtpmap:102 ILBC/8000
a=rtpmap:0 PCMU/8000
a=rtpmap:8 PCMA/8000
a=rtpmap:105 CN/16000
a=rtpmap:13 CN/8000
a=rtpmap:110 telephone-event/48000
a=rtpmap:113 telephone-event/16000
a=rtpmap:126 telephone-event/8000



SDP Answer: 

v=0
o=linus 0 1 IN IP4 170.133.146.100
s=-
c=IN IP4 170.133.146.100
b=TIAS:664000
t=0 0
a=ice-lite
m=video 5004 UDP/TLS/RTP/SAVPF 108
c=IN IP4 170.133.146.100
b=TIAS:600000
a=content:main
a=sendrecv
a=rtpmap:108 H264/90000
a=fmtp:108 profile-level-id=42400C;packetization-mode=1;max-mbps=27600;max-fs=920;max-fps=3000;max-br=600;max-dpb=891;level-asymmetry-allowed=1
a=rtcp-fb:* nack pli
a=rtcp-fb:* ccm fir
a=extmap:3/sendrecv urn:ietf:params:rtp-hdrext:toffset
a=extmap:5/sendrecv urn:3gpp:video-orientation
a=rtcp-mux
a=label:200
a=mid:0
a=ice-ufrag:+JfqYsKf
a=ice-pwd:mhPmUqLjWtTcJKqjKGTj9ZpRRvmtKGyo
a=setup:passive
a=fingerprint:sha-1 F7:E7:80:0A:F5:CF:63:BD:14:E4:29:82:DC:D2:AD:60:77:91:2B:08
m=audio 5004 UDP/TLS/RTP/SAVPF 98 101
c=IN IP4 170.133.146.100
b=TIAS:64000
a=content:main
a=sendonly
a=rtpmap:98 opus/48000/2
a=fmtp:98 maxplaybackrate=48000;maxaveragebitrate=64000;stereo=1
a=rtpmap:101 telephone-event/8000
a=fmtp:101 0-15
a=rtcp-mux
a=label:100
a=mid:1
a=ice-ufrag:UqIo8b+I
a=ice-pwd:Ufbaiwno+mb/3obcHwTQuzMw4yh3ynX2
a=setup:passive
a=fingerprint:sha-1 F7:E7:80:0A:F5:CF:63:BD:14:E4:29:82:DC:D2:AD:60:77:91:2B:08

**Comment by rahulk131** [comment] 2020-05-18 19:56
Also, the implementation picks the height/width/framerate. So it doesn't run into the floating-point comparison inaccuracies you've mentioned above.

**Comment by rahulk131** [comment] 2020-05-19 19:01
An update: I used Wireshark to monitor the packets received by the remote peer from the Hololens device. It looks like the video frames are not received by the remote peer.

Why might this happen? Why might the HoloLens not be sending out the video frames? Like I mentioned above, there is no issue in with the playback of local video on the Hololens. Also, the LocalVideoTrack callbacks when a new frame is received is successful. So the video signal from the hololens camera appears to be successfully delivered to the app.

**Comment by rahulk131** [comment] 2020-05-21 10:08
I am using Release 1.0. Might there be any advantage in moving to the current "Master", at least towards resolving this issue?

**Comment by djee-ms** [comment] 2020-05-21 12:30
I am a bit confused by your SDP message; one of them is likely from MixedReality-WebRTC/libwebrtc, but the other doesn't look like it is. Also I am not an SDP expert but it looks to me like the answer is invalid. The offer has codec H264/90000 with payload type number 100, and the answer replies with H264/90000 at payload type number 108. But the RFC seems to say that number shouldn't change (and I never saw it changed in my experience)

https://tools.ietf.org/html/rfc3264#page-10:
> In the case of RTP, if a particular codec was referenced with a specific payload type number in the offer, that same payload type number SHOULD be used for that codec in the answer.

So I am wondering if this is the issue. What library/software generated the answer?

> An update: I used Wireshark to monitor the packets received by the remote peer from the Hololens device. It looks like the video frames are not received by the remote peer.
> Why might this happen? Why might the HoloLens not be sending out the video frames?

You are drawing hasty conclusions no? You say Wireshark shows no video frames received; how can you tell that the frames are not sent in the first place, and this is not an issue with network losses, firewall, etc.? I _think_ it's not because I _think_ both incoming and outgoing video feeds use the same port and you say one of them work, but still that's not 100% conclusive to me.

> Might there be any advantage in moving to the current "Master", at least towards resolving this issue?

We don't know what the issue is, so I can't tell what moving to `master` would change.

**Comment by rahulk131** [comment] 2020-05-25 06:27
> I am a bit confused by your SDP message; one of them is likely from MixedReality-WebRTC/libwebrtc, but the other doesn't look like it is. Also I am not an SDP expert but it looks to me like the answer is invalid. The offer has codec H264/90000 with payload type number 100, and the answer replies with H264/90000 at payload type number 108. But the RFC seems to say that number shouldn't change (and I never saw it changed in my experience)
> 
> https://tools.ietf.org/html/rfc3264#page-10:
> 
> > In the case of RTP, if a particular codec was referenced with a specific payload type number in the offer, that same payload type number SHOULD be used for that codec in the answer.
> 

That's a good catch. I am no SDP expert either. However, there are also some references on the internet to the contrary - that they don't need to match: https://lists.w3.org/Archives/Public/public-webrtc/2016Jun/0077.html

Just FYI. I have no idea if this is accurate, though it appears to be from the Google Chrome team.

I'm continuing to look into this in more detail.

> So I am wondering if this is the issue. What library/software generated the answer?

When a Win 10 Laptop is running TestAppUWP, there is no issue with the video. The RTP payload types are still 100 and 108, and the video works fine. The issue arises only when a HoloLens 2 device is running TestAppUWP.

So I doubt this is the issue. TestAppUWP is talking to a Webex media server. This is what generated the answer. The media server seems to be implementing ICE-lite and SFU. 


> > An update: I used Wireshark to monitor the packets received by the remote peer from the Hololens device. It looks like the video frames are not received by the remote peer.
> > Why might this happen? Why might the HoloLens not be sending out the video frames?
> 
> You are drawing hasty conclusions no? You say Wireshark shows no video frames received; how can you tell that the frames are not sent in the first place, and this is not an issue with network losses, firewall, etc.? I _think_ it's not because I _think_ both incoming and outgoing video feeds use the same port and you say one of them work, but still that's not 100% conclusive to me.

Fair point. However, I doubt they are network losses since the issue is reproducible at various times. 

It is possible that the media server is receiving the video frames, but for some reason is not sending out those frames to my client. I've raised this with the media server team to see if they can find out if this is happening - I'm yet to hear back from them.

But again, I don't see why this would work on a laptop, but not Hololens 2. These factors mainly pointed me to the hypothesis that perhaps the Hololens 2 is itself not sending out frames.

> > Might there be any advantage in moving to the current "Master", at least towards resolving this issue?
> 
> We don't know what the issue is, so I can't tell what moving to `master` would change.

Is the code that sends out local frames exposed in the master? Can I put some logging there to ensure that that code executes on the Hololens? I couldn't find this in the release/1.0.3 - was wondering if master exposes some of these.

I appreciate very much your prompt and continued support in these forums. I was also wondering if there's any way we can get on a call to resolve this. Thanks.

**Comment by rahulk131** [comment] 2020-05-29 06:17
Closing this issue as I was able to get this working.

Unfortunately, I'm not certain what the problem was. I solved it by rewriting the app removing unnecessary aspects for our use case - this included removing the local media player, and initializing remote video player as early as possible. I used the nuget release/1.0.3 packages.

Thanks for this library and your continued support :)

**Closed** 2020-05-29 06:17 UTC
Labels: need info
