### ISSUE TITLE
H.264 video quality very low for a long time after startup

### ISSUE THREAD

**Issue by fibann** [microsoft/MixedReality-WebRTC#107] opened 2019-10-22 10:16 UTC
By default the H264 encoder code uses the min bitrate as starting bitrate, which leads to very poor image quality at the beginning of the stream.  The problem is compounded by the fact that:
1. the bitrate is changed through stopping the stream, resetting the whole Media Foundation pipeline and restarting the stream; this takes a long time and causes visible stuttering
2. the min interval between successive resets is set to 15s (supposedly to avoid a lot of stuttering in one go) which has the side effect of making significant rate changes take a very long time.

There are several ways we can address this:
- avoiding a full pipeline reset by setting https://docs.microsoft.com/windows/desktop/DirectShow/avenccommonmeanbitrate-property instead when only a bitrate change is needed (which is most times)
- initialize the new pipeline while the old one is still encoding (not sure if this is possible or there are limitations, especially with hardware encoders)
- expose the start/min bitrate through the native API and have the user/high-level API set it to a higher value (depending on e.g. the resolution).

**Comment by eirikhollis** [comment] 2019-11-04 13:21
@djee-ms @fibann 
I've been trying to modify the min/start/max bitrate to varying values, and can't seem to fix the blcokiness of the video sent from HL. I'm referring to the `PeerConnection.SetBitrate` method which addresses the following sentence mentioned above
```
expose the start/min bitrate through the native API and have the user/high-level API set it to a higher value (depending on e.g. the resolution).
```
I notice a significant lack in quality when setting min/start/max to 0.1mpbs, and some increase when setting min to 0.1mbps, start to 1mbps and max to 10mbps. 
I've uploaded a screenshot from a 720p30 stream with min/start/max all set to 10mbps:
![image](https://user-images.githubusercontent.com/30655189/68123734-0df07c00-ff0e-11e9-850f-4c5249113fcf.png)

Is this normal? Or am I experiencing something a lot more severe when what the issue is?
Both connection endpoints are located with 3 meters of a powerful router and I've tried varying webcameras. The issue is not present in Unity using VP8. Only H264 on UWP.

**Comment by djee-ms** [comment] 2019-11-04 15:10
Yes H.264 hardware encoding still has issues on UWP and we're not sure yet why the encoder sometimes seems to struggle, and some other times works fine. Although 0.1mpbs is probably too low, with 10Mbps your blockiness seems more severe than what we usually see. What device are you using? Is it some PC/Laptop or HoloLens 1? How is the CPU load on your app? Can you reproduce the same issue with TestAppUWP, or only with your app?

I'm not an expert on H.264 but I've seen after some initial adjustment some pretty good quality around 2.2-2.8Mbps (also 720p30) on a test call between Europe and US using TestAppUWP, so the bandwidth is probably not the main issue here. Still `SetBitrates()` seems to help in some uses. We are still working on it.

**Comment by eirikhollis** [comment] 2019-11-05 12:34
Currently testing with 720p30 with min/start set to 2Mbps and max set to 100Mbps. I'm receiving a single 480x640 15fps stream that is set to the default bit-rate configuration.

On UWP x86 on PC with a webcamera that can do up to 4k60, the CPU usage is around 50% on an i7-7700 processor. RAM usage around 150 MB. I have also tested a second webcamera, same issue.
The local image video feed within the app is crisp and clear with no blocking. On the receiving end, there is however blockiness and low bit-rate quality.
If I move a lot, it's the same as in the picture I sent before above. If I stand still, the quality improves to what is shown below:
![image (1)](https://user-images.githubusercontent.com/30655189/68206819-f4166e00-ffcd-11e9-849b-5b9890ea3b96.png)

On Hololens 1, the CPU usage is hovering in the 40-60% range and RAM usage around 160MB. The same scenario with the local video feed can be observed here, where the quality of the local video within the app is much better than what is shown on the receiving end. 
Tried to hold the HL as steady as possible and took a screenshot of what I would say is the best quality I can get out of the Hololens with 720p:
![image (2)](https://user-images.githubusercontent.com/30655189/68207838-21641b80-ffd0-11e9-9497-8d760064522d.png)

However, you rarely stand still with a HL on your head, so the general quality is somewhere in between this picture and the worst-case that was shown in my previous post. In other words, no text is readable, images are difficult to see, and small lines or details are almost completely remove by the  low bit-rate(?).

I haven't tested TestAppUWP yet, but how is this new information in comparison to what you've already seen?

**Comment by djee-ms** [comment] 2019-11-05 14:49
Not really, although this looks slightly worse in your case that the few other tests we did alone and with some third-party partner. But quality assessment is rather subjective. Yet I don't remember seeing blockiness when standing still; generally the image is crisp. When moving however it gets bad fast, and depending on the tests and apps used recover fast (<1 sec) or not.

More generally I do not think this is a limit of HoloLens 2 or H.264, and although I am not an expert in video encoding I feel like something is still wrong with the encoder code and we should be able to get something better than that, and so we are still working on trying to root cause that blockiness and reduce/eliminate it.

**Comment by eirikhollis** [comment] 2019-11-07 11:13
I've now tested with TestAppUWP, and noticed that the quality there is indeed a little bit better than what I was experiencing.

I went through the code of `LocalVideoSource.cs` and found this piece of code that I didn't have in my custom version of the same script.
```
if (Windows.ApplicationModel.Package.Current.Id.Architecture == Windows.System.ProcessorArchitecture.X86)
{
   // Holographic AR (transparent) x86 platform - Assume HoloLens 1
   localVideoSettings.videoProfileKind = PeerConnection.VideoProfileKind.VideoRecording; // No profile in VideoConferencing
}
```
Which apparently has a large effect on the blockiness of the video. I set up two Hololenses, one running TestAppUWP and one running my solution, and the quality is about the same. Nice!
Didn't realize setting a video profile would have such an effect? My mistake.

However, I do notice something in the start of a video session that I'ld like to point out. I connect against a web portal that automatically resizes the incoming video feed to the resolution it receives. So if the video is 720p, it resizes to 720p, if 896x504, it resizes to that, you get the point.
At the beginning of the 720p call from the Hololens, the video in the web portal is scaled to 720p, as it should be. However, a second later, the resolution drops to 896x504, and starts scaling in between 720p and 896x504 dynamically. Did you know about this?
After about 10 seconds, the resolution returns to a steady 720p and stays there for the duration of the call.
It seems like there is some automatic adjustment to the resolution at the start, maybe due to low bitrate or low bandwidth connection in the beginning of each call? Would love to hear your thoughts on this.

**Comment by djee-ms** [comment] 2019-11-07 12:34
There are multiple items here:
- Selecting a video profile has no effect on quality; but selecting a video profile does change the set of available resolutions, and so the default resolution too. So if you are not explicitly setting the **capture** resolution, then the default is used, which is I think 1280x720 without video profile and 896x504 with the `VideoRecording` one (guessing from memory here).
- The code you highlighted is here to force a lower resolution than the default no-profile one, to save on CPU and bandwidth. 896x504 is the recommended video resolution for video conferencing, where image quality needs to be balanced with latency (as opposed to _e.g._ recording a video to disk where users will want the best quality, and latency is irrelevant). By default the **capture** resolution will also be the start value of the **track** resolution as I know.
- As far as I know WebRTC video tracks have no fixed **track** resolution (that is, the resolution sent to the remote peer, as opposed to capture resolution from webcam, before eventual resizing and/or cropping); instead each frame carries its own resolution, such that it is possible in theory to have a different resolution for each frame. In practice I never observed it, probably because I was doing some tests on a connection with a high bandwidth, but what you describe does not surprise me.

I am not sure what you mean by "At the beginning of the 720p call from the Hololens"; what resolution is 720p referring to here, the webcam capture or something else?

Note: _track_ and _capture_ resolutions are not official terms; I just use them here to refer to the various parts of the media pipeline from webcam capture to sending to the remote peer.

**Comment by eirikhollis** [comment] 2019-11-07 12:51
- The resolution and framerate is explicitly set to 720p30, and that is also what is received in the portal (at least after 10 seconds). 
- There is in fact a quality difference with the video profile set to `VideoRecording` as opposed to leaving it blank, unless I'm misunderstanding something. It is the only line of code that has changed since the images I posted above.
- I have a very high bandwidth here, just ran a speedtest and got 580Mbps down and 500Mbps up. The resolution changes seem consistent each time I connect, e.g. they scale in the same pattern, which to me tells me that it's not related to fluctuating variables such as bandwidth or processing speed. I actually thought it might be related to the problems you are experiencing with H264 HW encoding.
- "At the beginning of the 720p call from the Hololens". Sorry, bad formulation. I initiate a call from the HL to the webportal. The resolution is explicitly set to 1280x720 30fps. After the call is established, and an image from the HL appears in the webportal, it is first correctly transmitted in 720p, but quickly falls to 896x504 for about 10 seconds before it goes up again to 720p. I can share my screen if you would like to observe it for yourself.
- If automatic resolution scaling is a feature, is it possible to expose an API to disable it?

**Comment by djee-ms** [comment] 2019-11-07 14:27
When you say "the resolution is explictly set", do you mean via [`LocalVideoTrackSettings`](https://microsoft.github.io/MixedReality-WebRTC/api/Microsoft.MixedReality.WebRTC.PeerConnection.LocalVideoTrackSettings.html)?

As I understand, automatic resolution scaling is not a feature, it's an hard-coded design choice of Google. There is no API I know of to do anything about it.  I am not even sure how the resolution scaling is determined (probably from the RTCP feedback loop based on the current quality and bandwidth use, but I don't know how in practice). This is the reason why in TestAppUWP the video container is initialized with the resolution of the first received frame, and cannot be initialized until the first frame is received. I searched for some time, and the resolution of the video track is not available anywhere except from within the frame itself, per frame.

**Comment by eirikhollis** [comment] 2019-11-07 15:24
Set via `LocalVideoTrackSettings` yes.

No worries on the resolution scaling, it's easy enough to work around that. 

I'll dig some deeper into the video quality and get back to you on my findings.

**Comment by Boo0317** [comment] 2019-11-19 02:29
I have the same problem on HL1,  In my case the video is blurred more than 30s.I tried to replace the original with the repo you provided and compile it, but it didn't work.Did I do something wrong?

**Comment by djee-ms** [comment] 2019-11-19 09:42
@Boo0317 are you using H.264? What repo are you trying to compile? There's not much you can do about this issue, we have some engineer working on it, we just need some time to find the root cause and fix it.

**Comment by Boo0317** [comment] 2019-11-19 11:57
@djee-ms,Yes,H.264 on HL1. Sorry ，I should @fibann ，I'm going to try to replace webrtc sdk with [this repo](https://github.com/webrtc-uwp/webrtc-windows/pull/71),but have no effect.

**Comment by fibann** [comment] 2019-11-19 12:25
@Boo0317 just to be 100% clear, that PR is for an external dependency and won't have any effect if just check it out, since dependencies are not rebuilt with MR-WebRTC by default. I'd recommend you to wait until a version of the NuGet packages including that change is released (hopefully soon). Otherwise you can try to build the dependencies locally, guidance is at https://microsoft.github.io/MixedReality-WebRTC/manual/building-core.html

In any case there are quite a few variables involved in this kind of issue. As said above the start bitrate is quite low, so even with that fix the automatic adjustment will take a few seconds to get up to speed. On a local wifi here it gets to a max of ~2.5Mbps and IMHO the quality is pretty good even at 720p@24 (not perfect, but noticeably better than at startup), but YMMV.

For anyone who needs it, I have made a branch that logs the actual bitrate out of the encoder: https://github.com/fibann/webrtc-windows/tree/h264-measure-bitrate. With this you should be able verify if the bitrate actually increases with time or not.

**Comment by Boo0317** [comment] 2019-11-20 02:09
> @ djee-ms，是的，HL1上的H.264。抱歉，我应该@fibann，我将尝试用[此存储库](https://github.com/webrtc-uwp/webrtc-windows/pull/71)替换webrtc sdk ，但没有效果。
好的，我将按照你的方式来尝试。

**Comment by Boo0317** [comment] 2019-11-20 02:18
@fibann Many thanks.I will try to build the project with your steps.Hope it works!

**Comment by djee-ms** [comment] 2019-12-10 11:28
With the most recent changes pushed to v1.0.2 NuGet packages, we believe the outstanding issues around low quality are now fixed. So I am closing this issue. Please feel free to reopen if there is still some problem with H.264 video quality being low for prolonged periods of time.

**Closed by djee-ms** 2019-12-10 11:28 UTC
Labels: bug
