### ISSUE TITLE
Support for connecting a WebRTC audio track to a Unity AudioSource

### ISSUE THREAD

**Issue by eanders-MS** [microsoft/MixedReality-WebRTC#92] opened 2019-10-04 00:29 UTC
Can you help me solve a mystery? Looking through the Unity sample project, I'm not seeing how the audio track is getting played. Scene doesn't have a Unity `AudioSource` MonoBehaviour. The code doesn't do anything with audio frames. How is audio getting to the speakers?

Context: In my project, I need to pipe the WebRTC audio track to a spatial audio emitter so that the audio is played at the media player's location in the scene. How can I pipe the audio track to a Unity `AudioSource`?

Thanks.

**Comment by djee-ms** [comment] 2019-10-04 08:28
Yes, this is not implemented, as pointed out in the documentation : https://microsoft.github.io/MixedReality-WebRTC/manual/unity-remoteaudiosource.html

Currently the audio output is managed internally in C++ by the WebRTC code which sends it out to the audio device directly for playback. Unity is never involved.

Implementing what you need, which is a perfectly valid use case that we should support, requires disabling the automatic audio output, and instead use a callback mechanism like video, then plug that somehow into Unity, likely via an `AudioSource` component. But I have not investigated the feasibility of this yet.

**Comment by eanders-MS** [comment] 2019-10-04 17:54
Thanks for the info. Is it on your roadmap to address this soon? :)

**Comment by stephenatwork** [comment] 2019-10-10 13:17
FWIW, you can disable automatic rendering of audio tracks in UWP by editing api.cpp:189
factoryConfig->audioRenderingEnabled = false; //was "true"

For desktop, I haven't confirmed this yet, but it seems to be the null AudioDeviceModule passed to webrtc::CreatePeerConnectionFactory which, if null, gets a default module created much later in WebRtcVoiceEngine::Init()

This still leaves the task of hooking up the frame event of course.

**Comment by stephenatwork** [comment] 2019-10-14 15:40
Linking #99

**Comment by stephenatwork** [comment] 2019-10-22 12:22
From #99 the RemoteAudioSource component can now play to a sibling AudioSource component.

The latency is much, much better than the previous AudioClip version thanks! And it shouldn't be too difficult to move the resampling code to a different thread if needed. (currently it happens lazily on the unity audio thread).

There are still some TODOs: Experimentally, Unity will only call OnAudioFilterRead if there is a sibling (Unity)AudioSource component. Is checking for the existence of the sibling (say on Play()) sufficient to toggle between direct & spatial audio? Or should we have an additional flag to explicitly state the users intention? We could give a sensible error message if the flag doesn't match the existence of AudioSource.

The original issue of webrtc sending audio direct to the speakers is still present. Currently there is a short echo as the audio is played twice. Will we want to control direct/spatial audio per track or per connection?

**Comment by fibann** [comment] 2020-04-24 11:02
The backbone for this has been implemented by #99.

Open issues:
- Add proper interface to enable/disable individual tracks
- Refactor AudioTrackReadBuffer to buffer an individual track, and tidy up interface according to comments (https://github.com/microsoft/MixedReality-WebRTC/pull/99#discussion_r405645085, https://github.com/microsoft/MixedReality-WebRTC/pull/99#discussion_r405707116, https://github.com/microsoft/MixedReality-WebRTC/pull/99#discussion_r405707691,https://github.com/microsoft/MixedReality-WebRTC/pull/99#discussion_r405712733)
- Tidy up Unity integration (https://github.com/microsoft/MixedReality-WebRTC/pull/99#discussion_r410115401)

**Comment by fibann** [comment] 2020-05-22 15:44
Closing this and opening separate issues for remaining work:
#371 Prevent automatic remote audio output on UWP
#372 Missed reads add audio delay in AudioTrackReadBuffer

**Closed by fibann** 2020-05-22 15:44 UTC
Labels: enhancement

**Comment by Felix-N** [comment] 2021-02-25 10:09
@fibann i'm curious about the current state.
the documentation (https://microsoft.github.io/MixedReality-WebRTC/manual/unity/unity-remoteaudiosource.html) refers to this ticket.

Is it yet possible to use spatial audio ?

**Comment by djee-ms** [comment] 2021-02-25 11:03
Docs is out of date.

**Comment by djee-ms** [comment] 2021-02-25 11:04
Logged as #683
