### ISSUE TITLE
Crash when using DataChannel

### ISSUE THREAD

**Issue by westbrma** [microsoft/MixedReality-WebRTC#628] opened 2020-11-24 22:59 UTC
I am able to use the DataChannel for some files but when I try to send too much data, the mrwebrtc.dll crashes. I hooked in to the BufferingChanged event to see if I was maxing out the buffer but this is not fired. I was running this through IIS, it takes down the entire site and I have to recycle the app pool.

[Version 2.0.2] with win10x64

**Comment by fibann** [comment] 2020-11-27 19:06
This seems a duplicate of https://github.com/microsoft/MixedReality-WebRTC/issues/590

**Closed by fibann** 2020-11-27 19:06 UTC
