### ISSUE TITLE
Unity Editor crash when stun server address misspell

### ISSUE THREAD

**Issue by Adrian-Pixels** [microsoft/MixedReality-WebRTC#387] opened 2020-05-29 12:00 UTC
**Describe the bug**
Unity Editor crash when I use the following direction: stun:stun.l.google.com:19302
I realize it is an error to add the initial "stun:" but there was no warning or error, Unity Editor just crash.

**To Reproduce**
1. Set stun:stun.l.google.com:19302 as stun Ice Server on the PeerConnection.
2. Hit play and Unity should crash.

**Expected behavior**
Warning or error about the bad stun direction.

**Environment**
 - Platform: Unity Editor, I didn't build.
 - Architecture: Unity Editor is x64 on Windows
 - Unity version (if applicable): 2019.2.21
 - Target device: Windows Desktop

**Comment by djee-ms** [comment] 2020-07-28 09:26
Hey @Adrian-Pixels sorry I think I missed your post, thanks for the feedback, we should at the very least not crash indeed. I'll see what we can do to make the experience better.

**Comment by fibann** [comment] 2020-07-30 10:56
@Adrian-Pixels which version of MR-WebRTC are you using? I tried reproducing on latest master (in the VideoChatDemo scene) and I don't get a crash, only an error in the log.

**Comment by fibann** [comment] 2020-07-31 09:56
Closing this as it is probably a duplicate of #122, reopen if it happens on latest master.

**Closed by fibann** 2020-07-31 09:56 UTC
Labels: bug
