### ISSUE TITLE
Audio problem in example application

### ISSUE THREAD

**Issue by Borysiakk** [microsoft/MixedReality-WebRTC#444] opened 2020-07-07 18:13 UTC
When opening the example application (TestNetCoreConsole )  with argument --audio, I can't  hear sound from my microphone.

Rec:

![REC](https://user-images.githubusercontent.com/26518631/86821971-4d69fc00-c08b-11ea-9598-62417dfe1cb9.png)

Play:

![PLAY](https://user-images.githubusercontent.com/26518631/86821995-54910a00-c08b-11ea-93cd-ab9183d83145.png)

**Comment by djee-ms** [comment] 2020-07-09 12:38
Hi @Borysiakk, 

I can reproduce but I am not sure yet why. I confirmed that the audio frames are received, but they seem silent. I suspect this is due to the fact that given how the example is currently setup the receiver is the caller, and the callee doesn't add the microphone track to the sending transceiver, so that transceiver sends silence instead. This is likely a regression brought with the changes for the new transceiver API. I will see if I can fix that in a simple way in this example. Note that even if you cannot hear yourself, the connection is still successfully established, and the audio transceiver successfully connected; just the audio from the microphone is not sent through that transceiver. In short this is a problem I think with this particular example's setup, and I don't think there's a bug in the library itself.

**Comment by fibann** [comment] 2020-07-27 17:41
This seems to be a duplicate of #192

**Closed by fibann** 2020-07-27 17:41 UTC
Labels: bug
