### ISSUE TITLE
Fail when run  .\gradlew assembleRelease

### ISSUE THREAD

**Issue by JiphuTzu** [microsoft/MixedReality-WebRTC#478] opened 2020-07-23 07:04 UTC
Got the message below. Any suggestion?
```
PS E:\TestProj\MixedReality-WebRTC\tools\build\android> .\gradlew assembleRelease
Starting a Gradle Daemon (subsequent builds will be faster)

> Task :webrtc-native:externalNativeBuildRelease FAILED
Build mrwebrtc arm64-v8a
ninja: error: 'E:/TestProj/MixedReality-WebRTC/tools/build/libwebrtc/webrtc/src/out/android/arm64/Release/obj/libwebrtc.a', needed by 'E:/TestProj/MixedReality-WebRTC/tools/build/android/webrtc-native/build/intermediates/cmake/release/obj/arm64-v8a/libmrwebrtc.so', missing and no known rule to make it

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':webrtc-native:externalNativeBuildRelease'.
> Build command failed.
  Error while executing process C:\Users\JC\AppData\Local\Android\Sdk\cmake\3.10.2.4988404\bin\cmake.exe with arguments {--build E:\TestProj\MixedReality-WebRTC\tools\build\android\webrtc-native\.externalNativeBuild\cmake\release\arm64-v8a --target mrwebrtc}
  ninja: error: 'E:/TestProj/MixedReality-WebRTC/tools/build/libwebrtc/webrtc/src/out/android/arm64/Release/obj/libwebrtc.a', needed by 'E:/TestProj/MixedReality-WebRTC/tools/build/android/webrtc-native/build/intermediates/cmake/release/obj/arm64-v8a/libmrwebrtc.so', missing and no known rule to make it


* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 8s
19 actionable tasks: 2 executed, 17 up-to-date
```

**Comment by djee-ms** [comment] 2020-07-23 09:28
Hi @JiphuTzu, what commit are you at?

**Comment by JiphuTzu** [comment] 2020-07-23 10:07
I cloned the newest master branch yesterday, and built 'libwebtrc.aar' by following the '/libwebrtc/README.md'. When I went on with option 2 in '/android/README.md', error appeared.

**Comment by djee-ms** [comment] 2020-07-23 10:17
Does the file mentioned in the error actually exists on disk?
```
E:/TestProj/MixedReality-WebRTC/tools/build/libwebrtc/webrtc/src/out/android/arm64/Release/obj/libwebrtc.a
```

**Comment by JiphuTzu** [comment] 2020-07-23 12:26
Yes, it's right there.

**Comment by djee-ms** [comment] 2020-07-23 12:39
I have no idea then. If the file is there but ninja complains it's not then there's not much I can do. We have a release pipeline for Unity building the Android platform and there's no issue.

Does the build works in Debug or FullDebug? That is, with _e.g._ `gradlew assembleDebug`?

**Comment by djee-ms** [comment] 2020-07-23 12:40
Also I see you're using a PowerShell prompt; I'd try with a regular cmd.exe instead. PowerShell is very not friendly to non-PS scripts, especially coming from the *nix world, and I've seen a lot of issues with PS which disappear by just switching to cmd.

**Comment by djee-ms** [comment] 2020-07-23 12:58
I've just tried in a VM with both Android Studio and command-line `gradew`, in Debug and Release, and everything works fine. It's possibly an issue with Windows-based cross-compiling. Are you using WSL2 (and not WSL1)?

**Comment by JiphuTzu** [comment] 2020-07-23 12:59
I tried cmd first, and got the same error. So I turn to PowerShell. Debug and FullDebug are the same. And I also built with AndroidStudio.

**Comment by JiphuTzu** [comment] 2020-07-23 13:00
Yes, I am using WSL2.

**Comment by djee-ms** [comment] 2020-07-23 13:01
Maybe try a clean build?

**Comment by JiphuTzu** [comment] 2020-07-23 13:02
Well, I'll try again.

**Comment by JiphuTzu** [comment] 2020-07-23 13:05
Er... Would you please send me a mrwebrtc.aar? I want to run my program on Android. Thanks.

**Comment by djee-ms** [comment] 2020-07-24 14:29
We just released a preview version of 2.0.0 which includes `mrwebrtc.aar` in the Unity package; please use that.
https://github.com/microsoft/MixedReality-WebRTC/releases/tag/v2.0.0-preview.1

**Comment by JiphuTzu** [comment] 2020-07-27 06:14
Great job!

**Comment by fibann** [comment] 2020-07-27 18:54
This seems to be solved (or not reproducible) so closing, reopen if necessary.

**Closed by fibann** 2020-07-27 18:54 UTC
