### ISSUE TITLE
Unity crashes on Windows when permission to the microphone is denied

### ISSUE THREAD

**Issue by HugoKampsSB** [microsoft/MixedReality-WebRTC#124] opened 2019-11-11 09:45 UTC
Hi!

I have a working RTC setup in Unity on my Windows laptop. One of my colleagues cloned the project but when pressing Play Unity closed down (even without the crash helper), without any logs. After some digging I found out it was due to the following error:

`Failed to complete start recognition system (hr = 0x80070005)`

Using this error I traced it to the Microphone access on this computer being disabled for all apps. 
![image](https://user-images.githubusercontent.com/37140671/68577396-4fce7480-0470-11ea-9e6e-1312716aa454.png)

After enabling it, it worked perfectly again :) Sadly I don't have any crash logs, because Unity closed down in a different way. 

I hope this helps!

**Comment by djee-ms** [comment] 2019-11-11 12:27
Unfortunately there is nothing we can do about that. When the internal Google implementation is initializing its audio module, on the very first call to any library API, it tries to find a microphone (any one) and will fail if none found. Right after that the caller asserts on the audio module pointer being NULL. This is admittedly a bug, or at least a questionable design decision that a microphone must be available, unless I am missing something here.

I tried adding the following checks, and they all failed to prevent the crash:
- Check in `LocalAudioSource.cs` that `Microphone.devices.Length` is non-zero; unfortunately Unity will report all available microphones, even if access to them is forbidden.
- Check `Application.HasUserAuthorization(UserAuthorization.WebCam)`, which incorrectly returns `true` (probably mapped to UWP capabilities, and returns always `true` on Desktop).

I am not happy about this answer, but unfortunately it seems the only way forward is to log a bug with Google and see what their devs have to say about this. Which may anyway pose some issue to integrate, because I have concerns they will not be willing to backport the fix to M71 (too old).

But more than that, the CoreAudio implementation of WebRTC is failing if **any** device fails to initialize. In particular in this case **all** devices are failing with `E_ACCESSDENIED` as seen in the debugger logs in Debug. I cannot find the reference again, but I already observed that questionable behavior and tried to report it, only to find that there was already a bug closed as "Won't fix" because the CoreAudio(1) is being deprecated in favor of a new CoreAudio2 rewrite, so devs do not want to spend resources on fixing the legacy one. Which makes it even less likely to get a fix in for the current issue. And CoreAudio2 is currently marked as experimental, so I am not very keen on switching to that for production code.

I would be glad to add some checks if anybody knows how to test for that Settings authorization programmatically. I couldn't find any way, and suspect there might not be one since the natural way would be to test for the `E_ACCESSDENIED` result code of the init function, which is currently being done internally and results in an assertion failure.

**Comment by djee-ms** [comment] 2019-11-11 12:53
Logged here : https://bugs.chromium.org/p/webrtc/issues/detail?id=11081

**Comment by michael-house** [comment] 2019-12-07 17:24
I'm seeing a similar issue, even when access is granted. Interestingly when I remote desktop into the dev machine and run the code, it works fine. Since remote desktop takes over the audio inputs/outputs, it certainly would seem to be related to that.
I don't have a microphone attached to the dev machine, but do have an emulated microphone from Steam's game streaming services.
I'd be happy to test the fix that comes from 11081, which appears to be committed and merged, but not yet in MixedReality-WebRTC.

**Comment by djee-ms** [comment] 2020-08-06 13:22
Switched to ADM2 by default, and confirmed that even with system-wide microphone access disabled the Windows Desktop tests do not crash like they used to do with ADM1.

**Closed by djee-ms** 2020-08-06 13:22 UTC
Labels: external bug

**Comment by kspark-scott** [comment] 2020-08-14 12:06
@djee-ms , I initially thought this fixed a long-standing issue for us, but now I suspect it does not.  I'm hoping you can clarify a few points for me.

The issue we have always had is that our UWP app will crash initializing WebRTC if no webcam is present.  It has become pressing for us because this is exactly the scenario that some "security conscious" customers are looking for -- they want to use laptops with no webcam, which works in our main scenarios where video is unidirectional from HoloLens to UWP app on desktop.

Do I understand correctly that this is different because (a) it applies to the desktop variant only, not UWP, and (b) because it deals only with audio and so crashes relating to the webcam would be something different?  If so, can you say anything about the no-webcam crash for UWP (e.g. are you aware of it, have you had a chance to investigate, ...)?

Thanks

**Comment by djee-ms** [comment] 2020-08-14 13:19
@kspark-scott yes this bug is unrelated, it's only for audio on Windows Desktop. Video on UWP should not require any permission if unused. @fiban has merged some change to fix #360 but again this is for UWP audio, not video. I don't know of any issue with video permission. Please open a new bug with details on the crash, we will see what we can do.

**Comment by kspark-scott** [comment] 2020-08-14 18:02
Thanks for the quick reply, but I am abashed to report that it was a false alarm.  When I went to re-test to get details for a new issue I found that the only problem was in our own code (very early code that predates me that I _think_ was attempting to work around similar problems in our original m68-based WebRTC).  A simple update to the media capture initialization settings was all it took to get this use case working perfectly.

**Comment by JacopoMarullo** [comment] 2020-12-15 18:25
Hi Jerome,
sorry for writing on a Closed issue. 

However, I'm looking forward to understand if the audio crash was solved by google WebRTC team specifically for the UWP platform. 

I want to clarify to you my scenario: i'm building for UWP plaftorm on a x64 Windows machine. 
On the target machine we can't have access to any microphone so we always receive crash when attempting to create a peer connection because no audio device was found.

Reading this thread on Google WebRTC -> [](https://bugs.chromium.org/p/webrtc/issues/detail?id=11081) it seems that they solved the issue now. I understand correctly? If yes how can I avoid the crash using MixedReality - WebRTC?

Thanks a lot if you will read everything 👍 
Jacopo

**Comment by djee-ms** [comment] 2020-12-16 18:04
This issue is for Windows Desktop only. This is unrelated with any UWP issue. Permissions models for Desktop and UWP are entirely disjoint. Your UWP bug is likely something like #360.

> was solved by google WebRTC team specifically for the UWP platform

Google's team does not do any work on UWP; they used to partially support UWP via contributions, but have abandoned any work for over a year, with all UWP CI builds on their side stopped.
